// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj0QOP8CClFMMqV8QDJ2pjiAmyvrno9EE',
    appId: '1:320780407455:web:da03bd68f84337fd7c88aa',
    messagingSenderId: '320780407455',
    projectId: 'home-assitant-4959c',
    authDomain: 'home-assitant-4959c.firebaseapp.com',
    storageBucket: 'home-assitant-4959c.appspot.com',
    measurementId: 'G-4V0F3FFY8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHDQLNgtdeUdSX3w-AUapX_ke9iLM8IrA',
    appId: '1:320780407455:android:742bfd7921be2eda7c88aa',
    messagingSenderId: '320780407455',
    projectId: 'home-assitant-4959c',
    storageBucket: 'home-assitant-4959c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYtIsRUVaYCk8LKlG5d7eW2Lr8OKUjLfI',
    appId: '1:320780407455:ios:786390acfe9f9d547c88aa',
    messagingSenderId: '320780407455',
    projectId: 'home-assitant-4959c',
    storageBucket: 'home-assitant-4959c.appspot.com',
    iosBundleId: 'com.example.homesense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYtIsRUVaYCk8LKlG5d7eW2Lr8OKUjLfI',
    appId: '1:320780407455:ios:786390acfe9f9d547c88aa',
    messagingSenderId: '320780407455',
    projectId: 'home-assitant-4959c',
    storageBucket: 'home-assitant-4959c.appspot.com',
    iosBundleId: 'com.example.homesense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj0QOP8CClFMMqV8QDJ2pjiAmyvrno9EE',
    appId: '1:320780407455:web:b87154e4b314afac7c88aa',
    messagingSenderId: '320780407455',
    projectId: 'home-assitant-4959c',
    authDomain: 'home-assitant-4959c.firebaseapp.com',
    storageBucket: 'home-assitant-4959c.appspot.com',
    measurementId: 'G-JPBF6K48ST',
  );
}
